import React, { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import MainLayout from "../../Layout/MainLayout";
import { authFetch } from "../../../utils/auth";
import { C } from "../../../utils/adminTheme";

const RANGE_OPTIONS = [
  { value: "past_7_days", label: "Past 7 Days" },
  { value: "past_30_days", label: "Past 30 Days" },
  { value: "this_month", label: "This Month" },
  { value: "last_month", label: "Last Month" },
];

const REPORT_LINKS = [
  {
    title: "Appointment Analytics",
    text: "Open detailed appointment, department, queue, AI, CSV, and PDF report.",
    path: "/admin/reports/appointments",
    accent: "#163a6b",
  },
  {
    title: "Medical Records Report",
    text: "Open read-only doctor-authored consultation records report.",
    path: "/admin/reports/medical-records",
    accent: "#1f7a52",
  },
  {
    title: "User Statistics Report",
    text: "Open live account distribution by role, including Frontdesk.",
    path: "/admin/reports/users",
    accent: "#5a3a8a",
  },
];

function intValue(value) {
  const parsed = Number.parseInt(value, 10);
  return Number.isFinite(parsed) ? parsed : 0;
}

function pct(part, total) {
  if (!total) return "0%";
  return `${Math.round((intValue(part) / intValue(total)) * 100)}%`;
}

function formatDate(date) {
  if (!date) return "Not available";
  return new Date(`${date}T00:00:00`).toLocaleDateString("en-PH", {
    year: "numeric",
    month: "short",
    day: "2-digit",
    timeZone: "Asia/Manila",
  });
}

function escapeHtml(value) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function getMetricCards(data) {
  const metrics = data?.metrics || {};
  const department = data?.highlights?.most_visited_department;
  const busiestDay = data?.highlights?.busiest_day;
  const totalAppointments = intValue(metrics.total_appointments);
  const completedVisits = intValue(metrics.completed_visits);
  const queueEntries = intValue(metrics.queue_entries);

  return [
    {
      label: "Total Appointments",
      value: totalAppointments,
      sub: `${intValue(metrics.confirmed_appointments)} confirmed, ${intValue(metrics.pending_appointments)} pending`,
      accent: C.navy,
    },
    {
      label: "Completed Visits",
      value: completedVisits,
      sub: `${pct(completedVisits, totalAppointments)} completion rate`,
      accent: C.teal,
    },
    {
      label: "Queue Entries",
      value: queueEntries,
      sub: "Recorded queue activity",
      accent: C.amber,
    },
    {
      label: "Most Visited Department",
      value: department?.department || "None",
      sub: department ? `${intValue(department.total)} appointment${intValue(department.total) === 1 ? "" : "s"}` : "No department data",
      accent: C.violet,
    },
    {
      label: "Busiest Day",
      value: busiestDay?.day_name || "None",
      sub: busiestDay ? `${intValue(busiestDay.total)} ${busiestDay.source === "queue" ? "queue entries" : "appointments"}` : "No day data",
      accent: C.blue,
    },
  ];
}

function buildPrintableReport(insights) {
  const metrics = insights?.metrics || {};
  const report = insights?.report || {};
  const departments = insights?.charts?.departments || [];
  const appointmentDays = insights?.charts?.appointments_by_day || [];
  const queueDays = insights?.charts?.queue_by_day || [];
  const sourceLabel = insights?.source === "gemini" ? "Gemini" : "Built-in fallback";

  return `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>QELCare AI Insights Report</title>
  <style>
    body { font-family: Arial, sans-serif; color: #17212b; margin: 36px; }
    h1 { color: #163a6b; margin: 0 0 6px; }
    h2 { color: #163a6b; margin-top: 28px; }
    .muted { color: #66758a; }
    .grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin: 22px 0; }
    .card { border: 1px solid #d8e2ee; border-left: 5px solid #163a6b; padding: 14px; border-radius: 6px; }
    .label { color: #66758a; font-size: 12px; text-transform: uppercase; }
    .value { font-size: 24px; font-weight: 700; margin-top: 4px; }
    table { width: 100%; border-collapse: collapse; margin-top: 10px; }
    th, td { border: 1px solid #d8e2ee; padding: 8px; text-align: left; vertical-align: top; }
    th { background: #f4f7fb; color: #163a6b; }
    li { margin: 6px 0; }
    @media print { body { margin: 20mm; } }
  </style>
</head>
<body>
  <h1>QELCare AI Insights Report</h1>
  <div class="muted">${escapeHtml(formatDate(insights?.range?.startDate))} to ${escapeHtml(formatDate(insights?.range?.endDate))}</div>
  <div class="muted">Generated by: ${escapeHtml(sourceLabel)}</div>
  ${insights?.fallback_reason ? `<div class="muted">Fallback reason: ${escapeHtml(insights.fallback_reason)}</div>` : ""}

  <div class="grid">
    <div class="card"><div class="label">Appointments</div><div class="value">${intValue(metrics.total_appointments)}</div></div>
    <div class="card"><div class="label">Completed Visits</div><div class="value">${intValue(metrics.completed_visits)}</div></div>
    <div class="card"><div class="label">Queue Entries</div><div class="value">${intValue(metrics.queue_entries)}</div></div>
    <div class="card"><div class="label">Completion Rate</div><div class="value">${pct(metrics.completed_visits, metrics.total_appointments)}</div></div>
  </div>

  <h2>Generated Report</h2>
  <p>${escapeHtml(report.summary || "No generated summary available.")}</p>
  <ul>${(report.bullets || []).map((bullet) => `<li>${escapeHtml(bullet)}</li>`).join("")}</ul>
  <p><strong>${escapeHtml(report.recommendation || "")}</strong></p>

  <h2>Department Visits</h2>
  <table>
    <thead><tr><th>Department</th><th>Appointments</th><th>Completed</th></tr></thead>
    <tbody>${departments.map((row) => `<tr><td>${escapeHtml(row.department)}</td><td>${intValue(row.total)}</td><td>${intValue(row.completed)}</td></tr>`).join("")}</tbody>
  </table>

  <h2>Clinic Days</h2>
  <table>
    <thead><tr><th>Day</th><th>Appointments</th><th>Queue Entries</th></tr></thead>
    <tbody>${appointmentDays.map((row) => {
      const queue = queueDays.find((item) => item.day_name === row.day_name);
      return `<tr><td>${escapeHtml(row.day_name)}</td><td>${intValue(row.total)}</td><td>${intValue(queue?.total)}</td></tr>`;
    }).join("")}</tbody>
  </table>

  <script>
    window.addEventListener("load", function () {
      setTimeout(function () { window.print(); }, 250);
    });
  </script>
</body>
</html>`;
}

function AnalyticsReports() {
  const navigate = useNavigate();
  const [range, setRange] = useState("past_7_days");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [insights, setInsights] = useState(null);

  const cards = useMemo(() => getMetricCards(insights), [insights]);
  const report = insights?.report;

  const generateInsights = async () => {
    try {
      setLoading(true);
      setError("");

      const response = await authFetch(`/analytics/ai-insights?range=${encodeURIComponent(range)}`);
      if (!response?.ok) {
        const payload = response ? await response.json().catch(() => ({})) : {};
        throw new Error(payload.message || "Failed to generate AI insights.");
      }

      const payload = await response.json();
      setInsights(payload.data || null);
    } catch (err) {
      setError(err.message || "Failed to generate AI insights.");
    } finally {
      setLoading(false);
    }
  };

  const downloadPdf = () => {
    if (!insights) return;
    const popup = window.open("", "_blank", "width=1000,height=800");
    if (!popup) {
      setError("Popup blocked. Allow popups, then click Download PDF again.");
      return;
    }
    popup.document.open();
    popup.document.write(buildPrintableReport(insights));
    popup.document.close();
  };

  return (
    <MainLayout pageTitle="AI Reports & Analytics" pageSubtitle="AI-assisted clinic operations reporting">
      <div style={{ display: "flex", flexDirection: "column", gap: 22 }}>
        <section style={{
          background: C.white,
          border: `1px solid ${C.line}`,
          borderRadius: 8,
          padding: 22,
          boxShadow: "0 2px 8px rgba(15,23,42,.04)",
        }}>
          <div style={{ display: "flex", justifyContent: "space-between", gap: 18, alignItems: "flex-start", flexWrap: "wrap" }}>
            <div>
              <div style={{ color: C.muted, fontSize: 11, fontWeight: 900, letterSpacing: ".08em", textTransform: "uppercase" }}>
                Admin Analytics
              </div>
              <h2 style={{ margin: "5px 0 6px", color: C.text, fontSize: 26, lineHeight: 1.2, fontWeight: 800 }}>
                AI Insights Report
              </h2>
              <p style={{ margin: 0, color: C.muted, fontSize: 14, lineHeight: 1.55, maxWidth: 720 }}>
                Generate a clinic operations summary from appointment, department, and queue activity.
              </p>
            </div>

            <div style={{ display: "flex", gap: 10, alignItems: "center", flexWrap: "wrap" }}>
              <select
                value={range}
                onChange={(event) => setRange(event.target.value)}
                disabled={loading}
                style={{
                  height: 42,
                  border: `1px solid ${C.line}`,
                  borderRadius: 8,
                  padding: "0 12px",
                  color: C.text,
                  background: C.white,
                  fontWeight: 700,
                  minWidth: 160,
                }}
              >
                {RANGE_OPTIONS.map((option) => (
                  <option key={option.value} value={option.value}>{option.label}</option>
                ))}
              </select>
              <button
                type="button"
                onClick={generateInsights}
                disabled={loading}
                style={{
                  height: 42,
                  border: `1px solid ${C.navy}`,
                  borderRadius: 8,
                  padding: "0 16px",
                  background: loading ? "#7389a6" : C.navy,
                  color: "#fff",
                  fontWeight: 800,
                  cursor: loading ? "not-allowed" : "pointer",
                  whiteSpace: "nowrap",
                }}
              >
                {loading ? "Generating..." : "Generate AI Insights"}
              </button>
              <button
                type="button"
                onClick={downloadPdf}
                disabled={!insights || loading}
                style={{
                  height: 42,
                  border: `1px solid ${insights ? C.navy : C.line}`,
                  borderRadius: 8,
                  padding: "0 16px",
                  background: insights ? C.white : "#edf2f7",
                  color: insights ? C.navy : C.muted,
                  fontWeight: 800,
                  cursor: insights && !loading ? "pointer" : "not-allowed",
                  whiteSpace: "nowrap",
                }}
              >
                Download PDF
              </button>
            </div>
          </div>
        </section>

        <section style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
          gap: 14,
        }}>
          {REPORT_LINKS.map((item) => (
            <button
              key={item.path}
              type="button"
              onClick={() => navigate(item.path)}
              style={{
                textAlign: "left",
                background: C.white,
                border: `1px solid ${C.line}`,
                borderTop: `4px solid ${item.accent}`,
                borderRadius: 8,
                padding: 16,
                minHeight: 116,
                cursor: "pointer",
                boxShadow: "0 2px 8px rgba(15,23,42,.04)",
                fontFamily: "inherit",
              }}
            >
              <div style={{ color: item.accent, fontSize: 16, fontWeight: 900, marginBottom: 8 }}>
                {item.title}
              </div>
              <div style={{ color: C.muted, fontSize: 13, lineHeight: 1.45 }}>
                {item.text}
              </div>
            </button>
          ))}
        </section>

        {error && (
          <div style={{
            background: "#fff2f4",
            color: C.red,
            border: "1px solid #f7c5cb",
            borderRadius: 8,
            padding: "12px 14px",
            fontSize: 13,
            fontWeight: 700,
          }}>
            {error}
          </div>
        )}

        <section style={{ display: "grid", gridTemplateColumns: "repeat(5, minmax(0, 1fr))", gap: 14 }}>
          {loading ? (
            Array.from({ length: 5 }).map((_, index) => <SkeletonCard key={index} />)
          ) : (
            cards.map((card) => <MetricCard key={card.label} card={card} />)
          )}
        </section>

        <section style={{
          display: "grid",
          gridTemplateColumns: "minmax(0, 1.15fr) minmax(320px,.85fr)",
          gap: 18,
          alignItems: "start",
        }}>
          <div style={{
            background: C.white,
            border: `1px solid ${C.line}`,
            borderRadius: 8,
            minHeight: 390,
            boxShadow: "0 2px 8px rgba(15,23,42,.04)",
            overflow: "hidden",
          }}>
            <div style={{ padding: "18px 20px", borderBottom: `1px solid ${C.line}`, display: "flex", justifyContent: "space-between", gap: 12, alignItems: "flex-start", flexWrap: "wrap" }}>
              <div>
                <h2 style={{ margin: 0, color: C.text, fontSize: 18 }}>Generated Report</h2>
                <p style={{ margin: "5px 0 0", color: C.muted, fontSize: 13 }}>
                  {insights ? `${formatDate(insights.range?.startDate)} to ${formatDate(insights.range?.endDate)} / ${insights.source === "gemini" ? "Gemini" : "Built-in fallback"}` : "Select a range and generate insights."}
                </p>
                {insights?.fallback_reason ? (
                  <p style={{ margin: "5px 0 0", color: C.amber, fontSize: 12, fontWeight: 700 }}>
                    Fallback reason: {insights.fallback_reason}
                  </p>
                ) : null}
              </div>
              {insights ? (
                <button
                  type="button"
                  onClick={downloadPdf}
                  disabled={loading}
                  style={{
                    height: 36,
                    border: `1px solid ${C.navy}`,
                    borderRadius: 8,
                    padding: "0 13px",
                    background: C.navy,
                    color: "#fff",
                    fontWeight: 800,
                    cursor: loading ? "not-allowed" : "pointer",
                    whiteSpace: "nowrap",
                  }}
                >
                  Download PDF
                </button>
              ) : null}
            </div>

            <div style={{ padding: 20 }}>
              {loading ? (
                <ReportSkeleton />
              ) : report ? (
                <ReportContent report={report} />
              ) : (
                <EmptyReport />
              )}
            </div>
          </div>

          <div style={{ display: "flex", flexDirection: "column", gap: 18 }}>
            <BreakdownPanel
              title="Department Visits"
              empty="No department activity in this period."
              rows={insights?.charts?.departments || []}
              labelKey="department"
              valueKey="total"
              accent={C.violet}
            />
            <BreakdownPanel
              title="Clinic Days"
              empty="No appointment activity in this period."
              rows={insights?.charts?.appointments_by_day || []}
              labelKey="day_name"
              valueKey="total"
              accent={C.blue}
            />
            <BreakdownPanel
              title="Queue Activity"
              empty="No queue activity in this period."
              rows={insights?.charts?.queue_by_day || []}
              labelKey="day_name"
              valueKey="total"
              accent={C.amber}
            />
          </div>
        </section>
      </div>

      <style>{`
        @media (max-width: 1180px) {
          section[style*="repeat(5"] {
            grid-template-columns: repeat(2, minmax(0, 1fr)) !important;
          }
          section[style*="1.15fr"] {
            grid-template-columns: 1fr !important;
          }
        }

        @media (max-width: 720px) {
          section[style*="repeat(5"] {
            grid-template-columns: 1fr !important;
          }
        }
      `}</style>
    </MainLayout>
  );
}

function MetricCard({ card }) {
  return (
    <article style={{
      background: C.white,
      border: `1px solid ${C.line}`,
      borderRadius: 8,
      padding: 16,
      minHeight: 118,
      boxShadow: "0 2px 8px rgba(15,23,42,.04)",
      borderTop: `4px solid ${card.accent}`,
      minWidth: 0,
    }}>
      <div style={{ color: C.muted, fontSize: 12, fontWeight: 800, marginBottom: 10 }}>{card.label}</div>
      <div style={{ color: C.text, fontSize: 24, lineHeight: 1.15, fontWeight: 900, wordBreak: "break-word" }}>
        {card.value}
      </div>
      <div style={{ color: C.muted, fontSize: 12, marginTop: 8, lineHeight: 1.4 }}>{card.sub}</div>
    </article>
  );
}

function SkeletonCard() {
  return (
    <article style={{ background: C.white, border: `1px solid ${C.line}`, borderRadius: 8, padding: 16, minHeight: 118 }}>
      <div style={{ width: "55%", height: 12, borderRadius: 999, background: "#e8eef6", marginBottom: 18 }} />
      <div style={{ width: "42%", height: 26, borderRadius: 8, background: "#e8eef6", marginBottom: 14 }} />
      <div style={{ width: "70%", height: 12, borderRadius: 999, background: "#e8eef6" }} />
    </article>
  );
}

function ReportSkeleton() {
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
      <div style={{ width: "100%", height: 16, borderRadius: 999, background: "#e8eef6" }} />
      <div style={{ width: "94%", height: 16, borderRadius: 999, background: "#e8eef6" }} />
      <div style={{ width: "72%", height: 16, borderRadius: 999, background: "#e8eef6" }} />
      <div style={{ height: 16 }} />
      {Array.from({ length: 5 }).map((_, index) => (
        <div key={index} style={{ width: `${86 - index * 7}%`, height: 14, borderRadius: 999, background: "#e8eef6" }} />
      ))}
      <div style={{ height: 16 }} />
      <div style={{ width: "88%", height: 16, borderRadius: 999, background: "#e8eef6" }} />
    </div>
  );
}

function ReportContent({ report }) {
  return (
    <div style={{ color: C.text, lineHeight: 1.65, fontSize: 14 }}>
      <p style={{ margin: "0 0 18px" }}>{report.summary}</p>
      <ul style={{ margin: "0 0 18px", paddingLeft: 20 }}>
        {(report.bullets || []).map((bullet, index) => (
          <li key={`${bullet}-${index}`} style={{ marginBottom: 8 }}>{bullet}</li>
        ))}
      </ul>
      <p style={{ margin: 0, fontWeight: 700 }}>{report.recommendation}</p>
    </div>
  );
}

function EmptyReport() {
  return (
    <div style={{
      minHeight: 245,
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      textAlign: "center",
      color: C.muted,
      gap: 8,
    }}>
      <div style={{ fontWeight: 900, color: C.text, fontSize: 18 }}>No report generated yet</div>
      <div style={{ maxWidth: 430, lineHeight: 1.5, fontSize: 14 }}>
        Choose a date range and generate clinic insights from real appointment and queue data.
      </div>
    </div>
  );
}

function BreakdownPanel({ title, empty, rows, labelKey, valueKey, accent }) {
  const max = Math.max(...rows.map((row) => intValue(row[valueKey])), 0);
  const filteredRows = rows.filter((row) => intValue(row[valueKey]) > 0);

  return (
    <section style={{
      background: C.white,
      border: `1px solid ${C.line}`,
      borderRadius: 8,
      boxShadow: "0 2px 8px rgba(15,23,42,.04)",
      overflow: "hidden",
    }}>
      <div style={{ padding: "15px 16px", borderBottom: `1px solid ${C.line}` }}>
        <h3 style={{ margin: 0, fontSize: 15, color: C.text }}>{title}</h3>
      </div>
      <div style={{ padding: 16, display: "flex", flexDirection: "column", gap: 12 }}>
        {filteredRows.length === 0 ? (
          <div style={{ color: C.muted, fontSize: 13, padding: "8px 0" }}>{empty}</div>
        ) : (
          filteredRows.map((row) => {
            const value = intValue(row[valueKey]);
            const width = max ? Math.max(6, Math.round((value / max) * 100)) : 0;
            return (
              <div key={`${title}-${row[labelKey]}`}>
                <div style={{ display: "flex", justifyContent: "space-between", gap: 10, fontSize: 13, marginBottom: 6 }}>
                  <span style={{ color: C.text, fontWeight: 700, minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
                    {row[labelKey]}
                  </span>
                  <span style={{ color: C.muted, fontWeight: 800 }}>{value}</span>
                </div>
                <div style={{ height: 8, background: "#edf2f8", borderRadius: 999, overflow: "hidden" }}>
                  <div style={{ width: `${width}%`, height: "100%", background: accent, borderRadius: 999 }} />
                </div>
              </div>
            );
          })
        )}
      </div>
    </section>
  );
}

export default AnalyticsReports;
